### ISSUE TITLE
Breaking change in PlanResources response

### ISSUE THREAD

**Issue by charithe** [cerbos/cerbos-sdk-ruby#18]
There are a couple of breaking change to `PlanResources` request and response protobufs in https://github.com/cerbos/cerbos/pull/960. 

- Request `resource` field object type has been renamed from `cerbos.engine.v1.PlanResourcesRequest_Resource` to `cerbos.engine.v1.PlanResourcesInput_Resource`: https://github.com/cerbos/cerbos/pull/960/files#diff-8381ea18c37e662312d10a519b5584dc306c354d32114df62f16d7f19c6b1063
- Type of `meta.filter` field of the response changes from `response.v1.PlanResourcesResponse_Filter` to `cerbos.engine.v1.PlanResourcesFilter`: https://github.com/cerbos/cerbos/pull/960/files#diff-6b1f0162d7474c86e63baa5946ace50297e21ef082ade0d27a811803cb033b3e

**Comment by haines** [comment]
Looks like those changes are backwards-compatible at the protocol level, so I think there are no changes required in the SDK (the internal generated code will reflect the renames next time it is regenerated, but it should continue to work with the old type names until then). There's a [nightly test run](https://github.com/cerbos/cerbos-sdk-ruby/actions?query=event%3Aschedule) which includes the `dev` tag, so we should pick up if there are any problems after https://github.com/cerbos/cerbos/pull/960 is merged.
